  dgb:
    image: ghcr.io/mmfpsolutions/digibyte:latest
    container_name: dgb
    network_mode: host
    stop_grace_period: 120s
    volumes:
      - /data/dgb/data:/data
    restart: unless-stopped
