  bch:
    image: ghcr.io/mmfpsolutions/bitcoincash:latest
    container_name: bch
    network_mode: host
    stop_grace_period: 120s
    volumes:
      - /data/bch/data:/data
    restart: unless-stopped
